### Generated Using Copilot
@UserManagementAPI_HostAddress = http://localhost:5026

### Get all users
GET {{UserManagementAPI_HostAddress}}/api/user
Accept: application/json

### Get user by ID (example: id = 0)
GET {{UserManagementAPI_HostAddress}}/api/user/0
Accept: application/json

### Add a new user
POST {{UserManagementAPI_HostAddress}}/api/user
Content-Type: application/json

{
  "username": "david",
  "password": "testpass123"
}

### Edit an existing user (example: id = 1)
PUT {{UserManagementAPI_HostAddress}}/api/user/1
Content-Type: application/json

{
  "username": "bob_updated",
  "password": "newpassword456"
}

### Delete a user (example: id = 2)
DELETE {{UserManagementAPI_HostAddress}}/api/user/2
